### ISSUE TITLE
특정 IP에 대하여 예외 처리가 되었으면 합니다.

### ISSUE THREAD

**Issue by han507** [skplanet/secuip#1]
block 조건을 만족하여 특정 URI의 요청이 block 되는 상황에서
미리 예외처리 설정을한 IP는 접근을 허용 할 수 있는 기능이 있었으면 좋겠습니다.

<Location 원하는 URI 경로>
  SecuipEnabled on
  SecuipDurationSecond 30 
  SecuipMaxCallCount 4 
  SecuipBlockSecond 60
  SecuipExcept 172.22.202.11,192.168.111.23  <== 요런식으로 설정?
  SecuipBlockResponseCode 403  
</Location>

**Comment by sjang** [comment]
Hello,

What you want is a sort of whiteList IP which will not be blocked.

I will support it by this week.

See you~

**Comment by sjang** [comment]
I added the feature.
