### ISSUE TITLE
불규칙적으로 apache process를 folk 하는것 같습니다.

### ISSUE THREAD

**Issue by han507** [skplanet/secuip#2]
# 우선 설정은 이렇게 했습니다.

SecuipRedisQueueEnabled on
SecuipRedisIP ...
SecuipRedisPort 19010
SecuipRedisPassword "..."
SecuipRedisInitCount 5

```
<LocationMatch "...">
    SecuipEnabled on
    SecuipDurationSecond 10
    SecuipMaxCallCount 16
    SecuipBlockSecond 1200
    SecuipBlockResponseCode 403
</LocationMatch>
```
# error 로그에  아래와 같이 나오고, httpd 프로세스를 재 시작하는것 으로 보입니다.

[Tue Aug 11 09:27:48 2015] [error] redis client initializaion.(apache child. PID:[24720])
[Tue Aug 11 09:27:48 2015] [error] init redis for secuip:[0], PID:[24720]
[Tue Aug 11 09:27:48 2015] [error] init redis for secuip:[1], PID:[24720]
[Tue Aug 11 09:27:48 2015] [error] init redis for secuip:[2], PID:[24720]
[Tue Aug 11 09:27:48 2015] [error] init redis for secuip:[3], PID:[24720]
[Tue Aug 11 09:27:48 2015] [error] init redis for secuip:[4], PID:[24720]
[Tue Aug 11 09:45:38 2015] [error] redis client initializaion.(apache child. PID:[28858])
[Tue Aug 11 09:45:38 2015] [error] init redis for secuip:[0], PID:[28858]
[Tue Aug 11 09:45:38 2015] [error] init redis for secuip:[1], PID:[28858]
[Tue Aug 11 09:45:38 2015] [error] init redis for secuip:[2], PID:[28858]
[Tue Aug 11 09:45:38 2015] [error] init redis for secuip:[3], PID:[28858]
[Tue Aug 11 09:45:38 2015] [error] init redis for secuip:[4], PID:[28858]
1. 어떤 이유로 httpd 프로세스를 재시작하는지 궁금합니다.
2.  어떤 주기로 프로세스를 재시작 하는건지 궁금합니다.
3.  고 부하 상황에서 프로세스 재시작이 트래픽 처리에 지장을 주지 않을까하는 생각도 듭니다.

봐주셔서 감사합니다 !!

**Comment by sjang** [comment]
It depends on httpd.conf.

Apache has two mode. prefork single thread and multithread.

Below is two configurations for them.

```
<IfModule mpm_prefork_module>
    StartServers         45
    ServerLimit        3072
    MinSpareServers      30
    MaxSpareServers      60
    MaxClients         2048
    MaxRequestsPerChild   1024
</IfModule>

<IfModule mpm_worker_module>
    StartServers         25
    ServerLimit        1024
    MaxClients         3060
    MinSpareThreads      60
    MaxSpareThreads      80
    ThreadsPerChild      20
    MaxRequestsPerChild   1024
</IfModule>
```

In this case, MaxRequestsPerChild is important.

The directive, MaxRequestsPerChild means that if one httpd handled this count(1024), the httpd process will restart.

Secuip module has a few operations, which is begun when new httpd starts.
And there are some loggings at the moment, like initializing redis connection.

Please, check your configuration.

**Comment by han507** [comment]
감사합니다.    

"MaxRequestsPerChild 0" 으로 설정되어 있지만

부하에 따라 MinSpareThreads, MaxSpareThreads 설정의 영향으로 httpd가 kill, folk 될 수 있을것 같습니다.

secuIP 를 의심해서 죄송합니다.^^
