### ISSUE TITLE
apache 프로세스 종료 없이 모듈파일을 변경하다 "segmentation fault"  발생 했습니다.

### ISSUE THREAD

**Issue by han507** [skplanet/secuip#3]
우선 비상식적인 작업을 해놓고 에러가 발생한다며 이슈를 재기하여 죄송합니다.
추후에는 안전하게 아파치 셧다운후 작업을 하겠습니다.
이번 건으로 장애를 유발하여 상세한 원인 파악이 필요한 상황입니다 ㅠㅠ
# 작업 내용 및 현상
1. 구 버전의 secuip 최신 빌드로 적용 결정
2. 기존 아파치 작업 경험상 DSO 모듈은 재기동시 읽어드리므로 apache 기동중에 작업해도 무방하다고 판단
3. 최신 소스를 서버에 옮기고 컴파일하여 아래 명령으로 덮어씀
   - cp libhiredis.so /app/apache/modules
   - cp mod_secuip.so /app/apache/modules
4. httpd 가 코어 떨구며 에러로그에  "sehmentation fault"  발생후  apache 비정상 동작하며 요청을 처리하지 못함
# 문의

원인파악을 위해 같은 시나리오로 재현 테스트를 했지만 아직 재현되지 않고있습니다.
혹시 위 문제가 발생 할 수 있는 상황은 어떤게있을까요?

감사합니다.

**Comment by sjang** [comment]
(이 부분은 영어가 딸려서 한글로 적어야겠네요.)

아파치 프로세스는 일반적으로 mod_로 시작하는 모듈 라이브러리와 같이 링크되지 않습니다.
그러므로, 모듈 라이브러리에 대해서는 dynamic loading를 통해서 그 라이브러리가 제공하는 함수를 symbol table로 만듭니다.

예상하기로는.... 떠 있던 아파치 프로세스가 symbol table에 따라 해당 어드레스에 있는 함수를 호출 했는데, mod_secuip.so 가 바뀌면서 해당주소를 통해서 실행되어야하는 실제 함수가 없었을거 같습니다.
보통은 함수명이 동일한 상태로 수정된 라이브러리라면, symbol table 상에 주소가 바뀌지는 않지만 실제 실행되는 스택은 달라질 것입니다. 이 경우에는 해당함수가 비이상동작할텐데 구체적으로 어떤일이 일어날지는 장담할 수 없습니다.

본 경우는 mod_secuip.so가 업데이트 되면서 symbol table 상의 함수주소가 달라졌을 겁니다. mod_secuip.so는 아파치에서 제공하는 API를 통해서 함수를 등록하는데, 그 등록하는 API가 github에 있는 소스의 것은 가지고 계신 것과 다릅니다. 따라서, symbol table 상에 주소가 존재하지 않았을 가능성이 높고, 그래서 프로그램이 falut 내면서 죽은 것으로 예상됩니다.

**Comment by han507** [comment]
감사합니다. 

Apache가 DSO 모듈을 로딩하는 시점이 httpd 의 기동 시점이라고만 알고있었는데.

제 생각이 짧았네요.~
